name: demobackend
services:
  demobackend:
    image: demobackend
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=DemoBackend;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: .
      dockerfile: DemoBackend/Dockerfile
    ports:
      - 64609:8080
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: demobackend
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC
    ports:
      - 64505:1433
    volumes:
      - mssql-data:/var/opt/mssql

networks:
  default:
    name: demobackend
volumes:
  mssql-data:
