name: demobackend
services:
  demobackend:
    image: demobackend
    container_name: api
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=demobackend;User Id=sa;Password=${DB_PASSWORD};
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: .
      dockerfile: DemoBackend/Dockerfile
    ports:
      - 64609:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: demobackend
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  default:
    name: demobackend
volumes:
  postgres-data:
